language: java

branches:
  only:
    - master
    - /^release.*$/

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

script: ./gradlew clean build jacocoTestReport

after_success: ./gradlew coveralls
